[package]
name = "day2_traits_and_modular_design"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustc_version_runtime = "0.3"